### ISSUE TITLE
A typo in the egpu setup script

### ISSUE THREAD

**Issue by joyliu37** [claudio-walser/egpu-setup#1]
Did you miss an "e" in this `gpu_connected` variable?
https://github.com/claudio-walser/egpu-setup/blob/ea1bd416e8a868687441b885884db3e65b2a1da3/egpu#L65

**Comment by claudio-walser** [comment]
Sure i did, thank you for pointing out. And thanks tacticaltechie for fixing it in https://github.com/claudio-walser/egpu-setup/pull/2
