### ISSUE TITLE
Do you USB and Ethernet ports work?

### ISSUE THREAD

**Issue by nickavem** [claudio-walser/egpu-setup#3]
I'm looking for an eGPU solution, and would like an "All-in-One" but have seen lots of issues about the Ethernet and USB ports reported. Wondeirng what your experience has been. I know this is probably not the best place to ask this, but I could think of no other way to contact you. Thanks!

**Comment by marbetschar** [comment]
@claudio-walser I do have the same question: Does USB and/or Ethernet work for you under Linux using the Chroma?

**Comment by claudio-walser** [comment]
Yes, they are both working fine on my fedora silverblue installation.
